export enum ActionTypes {
  GET_LUNA_PICTURES = "GET_LUNA_PICTURES",
  SELECT_LUNA_PICTURE = "SELECT_LUNA_PICTURE",
  // Manga
  GET_MANGA_DATA = "GET_MANGA_DATA",
  SELECT_MANGA = "SELECT_MANGA",
  SELECT_CHAPTER = "SELECT_CHAPTER",
  PREVIOUS_PAGE = "PREVIOUS_PAGE",
  NEXT_PAGE = "NEXT_PAGE"
}
