export enum MutationTypes {
  SET_DARK_MODE = "SET_DARK_MODE",
  SET_LUNA_PICTURES = "SET_LUNA_PICTURES",
  SET_LUNA_PICTURES_LOADING = "SET_LUNA_PICTURES_LOADING",
  SELECT_LUNA_PICTURE = "SELECT_LUNA_PICTURE"
}
