// Generated by https://quicktype.io
export enum Players {
  Kimossab = "Kimossab",
  Horta = "Horta",
  Fenrir = "Fenrir",
  Allexis = "Allexis",
  Mirai = "Mirai",
  AMPJ = "AMPJ",
  Marta = "Marta",
  Bernas = "Bernas",
  Sauron = "Sauron",
  Kurisu = "Kurisu",
}

export interface AMQPlaylist {
  roomName: string;
  startTime: string;
  songs: Song[];
}

export interface Song {
  songNumber: number;
  songInfo: SongInfo;
  correctGuess: boolean;
  wrongGuess: boolean;
  answer: string;
  correctCount: number;
  wrongCount: number;
  startPoint: number;
  videoLength: number;
  videoUrl: string;
  correctGuessPlayers: string[];
  listStates: ListState[];
}

export interface ListState {
  name: Players;
  status: number;
  score: number;
}

export interface SongInfo {
  animeNames: AnimeNames;
  artist: string;
  songName: string;
  type: number;
  typeNumber: number;
  annId: number;
  highRisk: number;
  animeScore: number;
  animeType: AnimeType;
  vintage: string;
  animeDifficulty: number;
  animeTags: string[];
  animeGenre: string[];
  altAnimeNames: string[];
  altAnimeNamesAnswers: string[];
  siteIds: SiteIDS;
}

export interface AnimeNames {
  english: string;
  romaji: string;
}

export enum AnimeType {
  Movie = "movie",
  Ona = "ONA",
  Tv = "TV",
}

export interface SiteIDS {
  annId: number;
  malId: number;
  kitsuId: number | null;
  aniListId: number;
}

export interface Anime {
  english: string;
  romaji: string;
  tags: string[];
  genre: string[];
  season: string;
  score: number;
  type: AnimeType;
}

export interface TournamentSong {
  name: string;
  artist: string;
  anime: Anime;
  difficulty: number;
}

export interface SongMeta {
  averageDifficulty: number;
  averageAnimeScore: number;
  repeatedSongs: number;
}

export interface GraphData {
  labels: string[];
  data: number[];
}

export interface Match {
  player: Players;
  score: number;
}

export interface GroupPlayer {
  player: Players;
  matches: Match[];
  wins: number;
  draws: number;
  losses: number;
}
