name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 21, 22, 23, 24]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: |
          npm ci
          npm run build
        name: Build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-v${{ matrix.node-version }}-release
          path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Zip artifact for deployment
        run: |
          (cd node-v20-release && zip -r "$OLDPWD/node-v20-release.zip" .)
          (cd node-v21-release && zip -r "$OLDPWD/node-v21-release.zip" .)
          (cd node-v22-release && zip -r "$OLDPWD/node-v22-release.zip" .)
          (cd node-v23-release && zip -r "$OLDPWD/node-v23-release.zip" .)
          (cd node-v24-release && zip -r "$OLDPWD/node-v24-release.zip" .)
      - name: Create Release
        run: gh release create ${{github.ref_name}} --generate-notes ./*.zip
